export { audioStorageCalculator } from './tool/audioStorageCalculator/entry';
export { bpmCalculator } from './tool/bpmCalculator/entry';
export { frequencyNoteConverter } from './tool/frequencyNoteConverter/entry';
export { metronome } from './tool/metronome/entry';
export { musicNoteEquivalency } from './tool/musicNoteEquivalency/entry';
export { phaseDistance } from './tool/phaseDistance/entry';
export { guitarStringTensionCalculator } from './tool/guitarStringTensionCalculator/entry';
export { setlistRuntimeCalculator } from './tool/setlistRuntimeCalculator/entry';
export { musicCategory } from './category';
import { audioStorageCalculator } from './tool/audioStorageCalculator/entry';
import { bpmCalculator } from './tool/bpmCalculator/entry';
import { frequencyNoteConverter } from './tool/frequencyNoteConverter/entry';
import { metronome } from './tool/metronome/entry';
import { musicNoteEquivalency } from './tool/musicNoteEquivalency/entry';
import { phaseDistance } from './tool/phaseDistance/entry';
import { guitarStringTensionCalculator } from './tool/guitarStringTensionCalculator/entry';
import { setlistRuntimeCalculator } from './tool/setlistRuntimeCalculator/entry';
import { mp3AOgg } from './tool/mp3AOgg/entry';
import { wavAOgg } from './tool/wavAOgg/entry';
import { oggAMp3 } from './tool/oggAMp3/entry';
import { oggAWav } from './tool/oggAWav/entry';
import { mp3AWav } from './tool/mp3AWav/entry';
import { wavAMp3 } from './tool/wavAMp3/entry';

export const ALL_ENTRIES = [audioStorageCalculator, bpmCalculator, frequencyNoteConverter, metronome, musicNoteEquivalency, phaseDistance, guitarStringTensionCalculator, setlistRuntimeCalculator, mp3AOgg, wavAOgg, oggAMp3, oggAWav, mp3AWav, wavAMp3];
